apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/comhendrik/k3s.git
    path: grafana
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

